# Site settings
title           : Code For Fort Collins
url             : "http://codeforfoco.org"
baseurl         : ""
copyright       : "2017"
email           : people@codeforfoco.org
github_username : codeforfoco
description: > # this means to ignore newlines until next yaml item
  Code for Fort Collins is a volunteer organization dedicated to using technology
  to solve challenges that charities, government agencies, and other
  groups in Fort Collins face. 

# Reading files
encoding: "utf-8"
markdown_ext: "md"

# Conversion
markdown: kramdown
highlighter: rouge

# Markdown processing
kramdown:
  input: GFM

# Sass/SCSS
sass:
  sass_dir: _sass
  style: nested
#  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.htm

# Outputting
permalink: pretty

# Plugins
gems:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jekyll-autoprefixer

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

# Serving
port          : 8080
